version: "3.9"

services:
  product-service:
    image: wiremock/wiremock:2.32.0
    command: --verbose
    volumes:
      - ./wiremock/product-service/stubs:/home/wiremock
    ports:
    - "8081:8080"
    